apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-deployment
  labels:
    app: pharmakart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmakart
      service: reminder
  template:
    metadata:
      labels:
        app: pharmakart
        service: reminder
    spec:
      containers:
        - name: pharmakart-reminder
          image: 719150847619.dkr.ecr.ca-central-1.amazonaws.com/pharmakart/reminder-svc:01eeeb0
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 50055
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "pharmakartdb"
            - name: PORT
              value: "50055"
            - name: SNS_TOPIC_ARN
              value: "your-sns-topic-arn"
            - name: SQS_QUEUE_URL
              value: "your-sqs-queue-url"
      imagePullSecrets:
        - name: regcred
