apiVersion: v1
kind: Service
metadata:
  name: reminder-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: reminder
  ports:
    - protocol: TCP
      port: 50055
      targetPort: 50055

