apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: pharmakart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmakart
      service: payment
  template:
    metadata:
      labels:
        app: pharmakart
        service: payment
    spec:
      containers:
        - name: pharmakart-payment
          image: 719150847619.dkr.ecr.ca-central-1.amazonaws.com/pharmakart/payment-svc:7a11d6d
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 50054
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "pharmakartdb"
            - name: PORT
              value: "50054"
            - name: FRONTEND_URL
              value: "frontend-service:3000"
            - name: STRIPE_SECRET_KEY
              value: "your-stripe-secret-key"
      imagePullSecrets:
        - name: regcred
