apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: payment
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054

