apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: pharmakart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmakart
      service: product
  template:
    metadata:
      labels:
        app: pharmakart
        service: product
    spec:
      containers:
        - name: pharmakart-product
          image: 719150847619.dkr.ecr.ca-central-1.amazonaws.com/pharmakart/product-svc:c79e137
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 50052
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "pharmakartdb"
      imagePullSecrets:
        - name: regcred
