apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: product
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052

