apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
