apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: authentication
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

