apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

