apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: pharmakart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmakart
      service: order
  template:
    metadata:
      labels:
        app: pharmakart
        service: order
    spec:
      containers:
        - name: pharmakart-order
          image: 719150847619.dkr.ecr.ca-central-1.amazonaws.com/pharmakart/order-svc:f3b3bba
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 50053
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "pharmakartdb"
            - name: PORT
              value: "50053"
            - name: PRODUCT_SERVICE_URL
              value: "product-service:50052"
            - name: PAYMENT_SERVICE_URL
              value: "payment-service:50054"
      imagePullSecrets:
        - name: regcred
