apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: pharmakart
spec:
  selector:
    app: pharmakart
    service: order
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053

